### ISSUE TITLE
Conda python 3.6

### ISSUE THREAD

**Issue by constantinpape** [svenpeter42/fastfilters#11]
Hi,

I need a conda python 3.6 version of fastfilters. 
However the meta.yaml allows builds only with 3.4 and 3.5:
https://github.com/svenpeter42/fastfilters/blob/master/pkg/conda/fastfilters/meta.yaml#L24

Is there any specific reason for this restriction?

**Comment by stuarteberg** [comment]
There's no particular reason.  I've just submitted a PR to update the recipe.  Until then, you can build with that branch, or you can just install a pre-built version from the `ilastik-forge` channel:

```
conda install -c ilastik-forge fastfilters
```

**Comment by svenpeter42** [comment]
fixed with PR #12 , thanks @stuarteberg  :)
